### PR TITLE
stomp input: copy headers from stomp message to event

### PR DESCRIPTION
**Pull request by jgabrielygalan**
Hi, please check this:
https://logstash.jira.com/browse/LOGSTASH-2015

This is my first experience with contributing to an open source project, so please let me know what I can do to proceed or help.

Thanks,

Jesus.

### CODE REVIEW

**Comment by wiibaa** [comment]
@jgabrielygalan could you please make sure that you signed the CLA? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

About **incorporating more doc**, this plugin is missing

**Comment by jgabrielygalan** [comment]
I have signed the CLA.

Regarding the doc: I understand now, I though you were referring to the option I added. I'm not the original creator of the plugin (obv :)). I'll try to come up with a general description of the plugin, and add it to this pull request.

**Comment by wiibaa** [comment]
@jgabrielygalan forgot to mention but as you will rework the PR a bit, could you please re-open it against the new repository https://github.com/logstash-plugins/logstash-input-stomp

**Comment by wiibaa** [comment]
@suyograo Dup of https://github.com/logstash-plugins/logstash-input-stomp/pull/2

**Pull request closed without merging**
