### PR TITLE
Add output plugin to push data to a Slack webhook

### PR DESCRIPTION
**Pull request by cyli**
Output plugin to post events to a slack channel.

### CODE REVIEW

**Comment by esolitos** [comment]
+1 @cyli publish this plugin in the group. :)

**Comment by cyli** [comment]
Sounds good.  :)  Will try to get this done sometime this week.

**Comment by esolitos** [comment]
PS: Have you got in plan to add support for the "attachments" field on Slack? Because I think I'll use it, so if you will not work on it I'll do it. :-)

M


    Esolitos Marlon

-----
Sent from mobile, sorry if there are typos or errors.
Write me back to me if there is any trouble in this email, I'll check on a larger screen (and a keyboard.)

**Comment by cyli** [comment]
First stab: https://github.com/cyli/logstash-output-slack

@esolitos: I attempted to add an attachment field there ^ - never used it before, but the docs say it's just an array?  Is that ok?

Could someone please validate that this is correct?   Also, someone mentioned on the `#logstash` channel that the docs for how to write plugins for 1.5 should be out soon, so I'm also fine with 'please just wait for the docs'  :)

**Comment by muktaa** [comment]
Hey @cyli this looks cool. please can you let me know how can i use this plugin into my config, to post output to slack?

**Comment by cyli** [comment]
@muktaa I guess they are changing the way plugins work in logstash, and this is not actually in the contrib tarball yet, so what I did was I put `slack.rb` in  `/<somepath>/logstash/outputs/slack.rb` and I ran logstash with the option `--pluginpath <somepath>`.

(http://logstash.net/docs/1.4.2/flags)

**Comment by cyli** [comment]
@muktaa Also I think the new logstash plugins (1.5) are just ruby gems, which I'm supposedly working on, but haven't had time to.  :)  If that is helpful to you in the immediate future (I don't know if it works for logstash < 1.5) I can try to make more time to do that soon.

**Comment by muktaa** [comment]
Thanks. Will check that out!

**Comment by timbunce** [comment]
Hi. Any news on this?

**Comment by cyli** [comment]
As per [these instructions](http://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html#_publishing_to_ulink_url_http_rubygems_org_rubygems_org_ulink_4), I have created the plugin here:

https://github.com/cyli/logstash-output-slack

It's been published as a ruby-gem, so should be installable.

I've also filed https://github.com/elastic/logstash/issues/3000 to have this reviewed and maybe moved into logstash-plugins.

@esolitos, I think I did the attachments stuff wrong, so I removed it for now - did you want them to come from the log event?

Anyway, closing this PR, as that plugin repo should probably supercede this PR :)

**Comment by suyograo** [comment]
thanks for the response folks. we'll move it here https://github.com/logstash-plugins/logstash-output-slack

**Pull request closed without merging**
