### PR TITLE
Add support for kinesis input and output streams

### PR DESCRIPTION
**Pull request by pmorton**

### CODE REVIEW

**Comment by lpetre** [comment]
@pmorton @kingkevin did you see the KCL Ruby library announcement? https://github.com/awslabs/amazon-kinesis-client-ruby

**Comment by innovia** [comment]
Hi can anyone please share how to manually merge and install this, i'd like to test this plugin very much

Thanks

Ami

**Comment by adience-code** [comment]
You're welcome to test my code:
https://github.com/adience-code/logstash-output-kinesis

It uses batch write and has an exponential backoff policy.

**Comment by suyograo** [comment]
@pmorton can you move this to the new plugin repos? how-to is here; https://www.elastic.co/guide/en/logstash/current/contributing-to-logstash.html#_adding_plugins

**Pull request closed without merging**
