### PR TITLE
implemented dictionary_url

### PR DESCRIPTION
**Pull request by angel9484**
New functionality. You can use a URL that needs to show a yml format,
then you don’t need to put an yml file for each logstash server and
maintain it. You only need to change the web service.

### CODE REVIEW

**Comment by wiibaa** [comment]
@angel9484 as mentioned in the README, this repo is now deprecated, can you please close this PR in favor of the one you already opened in the plugin repository https://github.com/logstash-plugins/logstash-filter-translate/pull/3. THanks

**Comment by angel9484** [comment]
Hi! I did the pull request in both repos. The reason because I updated this
is due we use 1.4.2 at work and some people may be in that situation.

Best regards !

**Comment by wiibaa** [comment]
@suyograo Dup of https://github.com/logstash-plugins/logstash-filter-translate/pull/3 vs logstash-contrib-1.4.3 ??

**Comment by suyograo** [comment]
At this point there are no plans to update the contrib for a 1.4.3 release. Will leave this open for now

**Pull request closed without merging**
