### PR TITLE
adds varnishncsa input

### PR DESCRIPTION
**Pull request by vitalis**
this pull request adds a varnishncsa input for simple logging event from Varnish cache.
more info on varnishncsa: 
https://www.varnish-cache.org/docs/3.0/reference/varnishncsa.html

here is an example of log message generated by the plugin:

``` json
{
  "_index": "logstash-2014.06.05",
  "_type": "varnishncsa",
  "_id": "rf2Fz8LUQ66IvD5jA63sXA",
  "_score": null,
  "_source": {
    "@timestamp": "2014-06-05T11:03:53.000+00:00",
    "request_url": "/v12/accounts/105.json",
    "response_time_microseconds": "0.022854",
    "response_time_seconds": "0",
    "request_protocol": "HTTP/1.1",
    "response_size": "3713",
    "request_method": "GET",
    "query_string": "?api[bundle]=com.miteleliteandroid&api[bver]=2.0.30&api[device_model]=SM-G3815&api[os_type]=android&api[os_version]=17&api[sig]=E38DEA0EFC6C83C56CF37C9194BC6E15&api[timestamp]=1401966231&api[udid]=644410ad46d94f13&api[uuid]=533c8d59b",
    "message": "GET http://admin.applicaster.com/v12/accounts/105.json?api[bundle]=com.miteleliteandroid&api[bver]=2.0.30&api[device_model]=SM-G3815&api[os_type]=android&api[os_version]=17&api[sig]=E38DEA0EFC6C83C56CF37C9194BC6E15&api[timestamp]=1401966231&api[udid]=644410ad46d94f13&api[uuid]=533c8d59b HTTP/1.1",
    "status": "200",
    "http_user": "-",
    "request_header_x_forwarded_for": "31.4.181.86",
    "request_header_user_agent": "-",
    "request_header_accept_language": "-",
    "request_header_host": "admin.applicaster.com",
    "request_header_referer": "-",
    "response_header_cache_control": "max-age=0, private, must-revalidate",
    "response_header_content_encoding": "-",
    "response_header_content_type": "application/json; charset=utf-8",
    "response_header_last_modified": "-",
    "varnish_time_firstbyte": "0.022815943",
    "varnish_hitmiss": "miss",
    "varnish_handling": "pass",
    "@version": "1",
    "source_host": "ip-10-140-168-41",
    "type": "varnishncsa",
    "tags": [
      "applicaster2"
    ]
  }
```

### CODE REVIEW

**Comment by mchugh19** [comment]
... and everything works now. Turns out kibana 4 requires you to hit the refresh button on mappings in order to pull in new resources.

**Comment by ninjada** [comment]
hi mchugh19,

Could you elaborate a bit more on how you managed to fix the stream error crashing logstash?

I Have tried running varnish 3.05, 3.06 and 4.02 on my test logstash-forwarder server, all versions cause the same error on the logstash server.

:message=>"Exception while running varnishncsa", :e=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3533:in `each'", "/opt/logstash/lib/logstash/inputs/varnishncsa.rb:65:in `run'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/lib/logstash/inputs/varnishncsa.rb:62:in `run'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:error}
{:timestamp=>"2015-02-06T12:14:00.981000+1100", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Varnishncsa type=>\"varnish-test\", format=>\"default\">\n  Error: closed stream", :level=>:error} 

Using same input config.

Anyone with any ideas?

**Comment by mchugh19** [comment]
@ninjada The mentioned crashing problem was eventually worked around by upgrading from varnish 3.0.3 to 3.0.6. The newer varnishncsa utility included output options for timestamp and response time, and it was 3.0.3's lack of those output options that was crashing the varnishncsa process. I would suggest running the command:
varnishncsa -F ' {"@timestamp":"%{%Y-%m-%dT%H:%M:%S%z}t","request_url":"%U","response_time_microseconds":"%D",
  "response_time_seconds":"%T","request_protocol":"%H","response_size":"%b",
  "request_method":"%m","query_string":"%q","message":"%r","status":"%s","http_user":"%u",
  "request_header_x_forwarded_for":"%{X-Forwarded-For}i","request_header_user_agent":"%{User-agent}i",  "request_header_accept_language":"%{Accept-Language}i","request_header_host":"%{Host}i","request_header_referer":"%{Referer}i",  "response_header_cache_control":"%{Cache-Control}o","response_header_content_encoding":"%{Content-Encoding}o",  "response_header_content_type":"%{Content-Type}o","response_header_last_modified":"%{Last-Modified}o",  "varnish_time_firstbyte":"%{Varnish:time_firstbyte}x","varnish_hitmiss":"%{Varnish:hitmiss}x",  "varnish_handling":"%{Varnish:handling}x"}'

to test. 

You should be able to track down what line is erroring out by adding some debugging print statements, like:
@logger.info("At line 20")

As far as the logstash conf goes, you should not need to define a text log. The point of this input is that it runs the varnishncsa command for you. Since varnish deals with high traffic sites, you might not want to take the I/O hit to write out to a file. 

My logstash conf to enable this input is simply:
input {
  varnishncsa {
    type => "cws-varnish"
    codec => json
  }
}

**Comment by ninjada** [comment]
thanks @mchugh19 will debug the varnishncsa output formatting.

I seem to be getting slightly confused though. If varnishncsa isn't writing to a log file, how should the logstash-forwarder configured? is any logstash-forwarder config needed agent-side? what interaction is happening? should it just be running daemonized?

is any further config needed on the logstash server aside from the varnishncsa.rb input? 

was 'seing constant /bin/sh varnishsca not found' errors as i didn't have varnishncsa installed. seems to have helped as i'm not seeing the error any more, however still not seeing logs coming through correctly yet.

**Comment by mchugh19** [comment]
@ninjada This logstash plugin runs the varnishncsa binary, and processes its output with logstash. Thus, you should not need to do anything other than ensure your version of varnishncsa supports the requested output options (as 3.0.6 does), and install this varnishncsa.rb file. 

Once that is setup, you simply need tell logstash about the varnishncsa input, as I specified earlier, and then startup the logstash service. It will handle the rest.

**Comment by ninjada** [comment]
@mchugh19 

Sorry, i must be doing something wrong. As far as i can tell i have all of that setup, i have the varnishncsa.rb at "/opt/logstash/lib/logstash/inputs", i have the right input conf setup, it registers as a plugin fine when starting logstash but I'm not seeing anything ingested from my remote servers running varnish and logstash-forwarder. 

What you're saying seems to describe log ingestion via varnishncsa running locally on a logstash server? 

Does this plugin on the logstash server communicate with remote hosts somehow to communicate with varnishncsa? From what I can tell the logstash server is passive and remote servers need to be told what to send in.

What are you supposed to do on the remote servers, do you run varnishncsa there as well? do you configure a harvester somehow? How is the varnishncsa output on a remote server meant to be sent to logstash?

**Comment by mchugh19** [comment]
@ninjada 
Ah, sounds like you might want to read a bit more about logstash. In our environment, we use logstash to ship logs off to an elasticsearch cluster. On our servers, we have logstash pull in text logs such as /var/log/messages, apache access logs, and now varnishncsa output. These are all defined as logstash inputs. 

We also define a logstash output. In our case this is a redis queue, from which our elasticsearch nodes slirp up the messages and index them in elasticsearch. From there we can use the kibana web interface to access the stuff in elasticsearch. 

Thus, in order for this input plugin to be useful to you, you will need to have an elasticsearch cluster working. Once you've got that, you will need to run logstash on each of your nodes in order to ship off the logs you care about. 


So in your case, since it sounds like you have multiple webservers, you would need to run logstash on each of them and also run this varnishncsa input plugin on each server running varnish. You would then need to define where each of these logstash clients should output the logs to. This will probably involve elasticsearch.

**Comment by ninjada** [comment]
@mchugh19 thanks man, that explains my deep confusion. testing it all out pre-prod with the ELK stack on a single server.. have been assuming logstash-forwarder is the agent for all situations.

**Pull request closed without merging**
